### ISSUE TITLE
Logo Design

### ISSUE THREAD

**Issue by zuuritaly** [krematas/soccerontable#1]
Hello!

I'm a graphic designer and I like to support open source projects. I would like to design a logo for your project if you interested, I will be happy to work with you! :)

Best Regards

Zuur

Graphic Designer

**Comment by seanvrar** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
Hi Zuur, Thanks for reaching out and excited to hear from you ! We are working on an arena-scale VR multiplayers project, called Interspace. To help you understand, I would make reference to The Void. and we have been thinking about redesign our logo to make it reflect our identity. Please let me know about your thoughts. 
Sincerely, 

    
        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #199cff;
            cursor: pointer;
        }
        a#ntes-pcmail-signature-default:active {
            text-decoration: underline;
            color: #246fce;
            cursor: pointer;
        }
    

                
                    
    
        font{
            line-height: 1.6;
        }
    

    
        font{
            line-height: 1.6;
        }
    

    
        font{
            line-height: 1.6;
        }
    

    
        font{
            line-height: 1.6;
        }
    
Sean Hwang   Chief Technology Officer  首席技術官ARTA SHENZHEN TECHNOLOGY   埃尔塔（深圳）科技有限公司  Add：31 Jia An Road, 12th Floor Room 1213, Bao’an District,   Shenzhen ,Guangdong, China地址：廣東省深圳市寶安區甲岸路31號十二樓1213室Tel 电话：010 - 58474329  Wechat 微信：279460501Site 网站:www.Artaology.comSTATEMENT OF CONFIDENTIALITYThe information and attachment(s) contained in this communication
are intended for the addressee only, and may be confidential and/or legally
privileged. If you have received this communication in error, please contact
the sender immediately, and delete this communication from any computer or
network system.




                


    On 6/20/2018 23:03，Zuur<notifications@github.com> wrote： 


Hello!
I'm a graphic designer and I like to support open source projects. I would like to design a logo for your project if you interested, I will be happy to work with you! :)
Best Regards
Zuur
Graphic Designer

**Comment by zuuritaly** [comment]
Hello @seanvrar  ,
Usually after the project owner accepts that I design the logo, I ask the following questions to assist me in the creative process:

Do you have something in your mind for the logo?
Do you want something specific for the logo?
What colors do you want in the logo?

With your answers I will design a logo for your project and if you like it you can keep it and used.

Best Regards

Zuur

**Comment by krematas** [comment]
Hello Zuur,
Thanks for your interest but currently we do not need a logo. 

Best,
Konstantinos
