### ISSUE TITLE
instancesegm: No such file or directory

### ISSUE THREAD

**Issue by xymsh** [krematas/soccerontable#11]
When I executed refining instance segmentation, I got the error.

`./soccer3d/instancesegm/instancesegm: No such file or directory`

The command line is

`./soccer3d/instancesegm/instancesegm --path_to_data $DATADIR/players/ --thresh 1.5 --path_to_model ./soccer3d/instancesegm/model.yml.gz`

I checked this directory. There is no `instancesegm` file under `soccer3d/instancesegm` directory.

I think the author might forget to compile, or forget to tell us.
The solution is to go to directory `soccer3d/instancesegm/`, and execute
`cmake .`
`make`

**Comment by krematas** [comment]
Did you run bash compile.sh (at the main directory)?

**Comment by xymsh** [comment]
Sorry, I didn't notice it before. 

Maybe it's better to be included in the `README.MD` as the first step of this project.

**Comment by hysoka79** [comment]
So when do I need to run the compile.sh??
run it before cmake . && make?

**Comment by krematas** [comment]
just bash compile.sh in the proper directory should work.
