### ISSUE TITLE
crash when running estimate_poses.py

### ISSUE THREAD

**Issue by rachillesf** [krematas/soccerontable#3]
Hi, thanks for sharing this great project.

I'm having this error when I run the estimate_poses.py

Traceback (most recent call last):
  File "estimate_poses.py", line 19, in <module>
    db.estimate_poses(openpose_dir=opt.openpose_dir)
  File "/home/lrvc/DeepStereo/soccer/soccerontable/soccer3d/core.py", line 270, in estimate_poses
    with open(join(join(self.path_to_dataset, 'tmp'), '{0}_pose.yml'.format(j))) as data_file:
IOError: [Errno 2] No such file or directory: '/home/lrvc/DeepStereo/soccer/dataset/barcelona/tmp/0_pose.yml'

and I couldn't find anywhere in the code where it creates the file 0_pose.yml. Is this in somewhat related to the openpose installation?

thanks for the help 
best

**Comment by krematas** [comment]
Hello,

It seems that openpose didn't output the pose files. Is your path_to_dataset/tmp dir empty? Or if it contains files, what's the name format? I will also check with newer versions of openpose if their output is in the same format (*_pose.yml) as mine.

Thanks!

**Comment by rachillesf** [comment]
My path_to_dataset/tmp contains the player's images. The file names are 0.jpg, 1.jpg ... 19.jpg.

I also rebuild my openpose installation with the BUILD_PYTHON flag and tested the binaries. It's working fine.

Unfortunately the estimate_poses.py error remains.

**Comment by krematas** [comment]
It seems that open pose doesn't either crashes or it doesn't saves the output .json files in the correct directory.

**Comment by krematas** [comment]
I know that some earlier versions didn't output in the specific format. I will try with the latest to see if this problem appears

**Comment by krematas** [comment]
Update master, it should work. the new openpose saves in different format the yml files, so I changed it to json
