### ISSUE TITLE
X error thrown out during simple visualization

### ISSUE THREAD

**Issue by HugoAutumn1024** [krematas/soccerontable#5]
Hello,thanks for sharing this project.
I got error when i want to excute simple_visualization.
The error stack like:
```
X Error of failed request: BadRequest (invalid request code or no su operation)
    Major opcode of failed request:１４９（RANDR）
    Minor opcode of failed request:8(RRGetScreenResources)
    Serial number of failed request:14
    Current serial number in output stream:14
```
I check the code ,it thrown out when python invoke the app.window() of glumpy moudle.
It seems like some incorrect configuration about driver. I have no idea.
Have you ever face this problem before? or do you have any idea?
Best wishes.

**Comment by krematas** [comment]
I didn't have this problem before, but I had occasionally problems with glumpy. My final visualizations were done in blender/unity.
