### ISSUE TITLE
Problem on _set_correspondences function

### ISSUE THREAD

**Issue by hysoka79** [krematas/soccerontable#7]

**Comment by krematas** [comment]
A gui should appear where the user clicks 4 keypoints between the input frame and a top view of a synthetic field. Did the gui appear to you?

**Comment by xymsh** [comment]
I have the similar problem.

` File "/home/--/Documents/lib/soccerontable/soccer3d/calibration/core.py", line 94, in _set_correspondences
    points3d[:, 0] = ((points3d[:, 0] - w2 / 2.) / w2) * W
IndexError: too many indices for array`

No gui appeared. How to solve it?

**Comment by hysoka79** [comment]
Thanks to krematas.
I found that it's that I'm using mac, so I need to download the X server and login with ssh -X
so that the gui will pop out.
 Don't know if it helps xymsh.
And when running openpose for the keypoints it needs to login by ssh -X -v

Btw thanks for the project~!

**Comment by xymsh** [comment]
I solved this problem by setting the matplotlib backend to 'TkAgg'. 
Specifically, I added the following code in `soccerontable/soccer3d/calibration/core.py`

`import matplotlib`
`matplotlib.use('TkAgg')`

Then the GUI appeared.
